Review feedback

diff --git a/commands/bash/container/change-permissions/change-permissions b/commands/bash/container/change-permissions/change-permissions
--- a/commands/bash/container/change-permissions/change-permissions
+++ b/commands/bash/container/change-permissions/change-permissions
@@ -2,21 +2,21 @@
 set -eu -o pipefail
 
 function change_permissions {
-	# If authentication is enabled, allow the user to switch permission levels if it is one of the
-	# $AUTHENTICATION_ALLOWED_CHANGE_ROLES
-	if ! "$AUTHENTICATION_ENABLED"; then
-		echo >&2 "aladdin: error: authentication is not enabled currently. update your aladdin-config to enable"
-		exit 1
-	fi
-	if [[ "$(jq -r --arg role $1 '. | index($role)' <<< $AUTHENTICATION_ALLOWED_CHANGE_ROLES)" == null ]]; then
-		echo >&2 "aladdin: error: this permission does not exist, or you are not allowed to change to it"
-		exit 1
-	fi
+    # If authentication is enabled, allow the user to switch permission levels if it is one of the
+    # $AUTHENTICATION_ALLOWED_CHANGE_ROLES
+    if ! "$AUTHENTICATION_ENABLED"; then
+        echo >&2 "aladdin: error: authentication is not enabled currently. update your aladdin-config to enable"
+        exit 1
+    fi
+    if [[ "$(jq -r --arg role $1 '. | index($role)' <<< $AUTHENTICATION_ALLOWED_CHANGE_ROLES)" == null ]]; then
+        echo >&2 "aladdin: error: this permission does not exist, or you are not allowed to change to it"
+        exit 1
+    fi
     kubectl config set-context "$NAMESPACE.$CLUSTER_NAME" --cluster "$CLUSTER_NAME" \
         --namespace="$NAMESPACE" --user "$1"
 }
 
-function help {
+function usage {
     cat <<-EOF
 		usage: aladdin change-permissions [-h] permission
 
@@ -29,7 +29,7 @@ function help {
 }
 
 if [[ $# -eq 0 || "$1" == "-h" || "$1" == "--help" ]]; then
-    help
+    usage
 else
     change_permissions "$1"
 fi
